apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasky-webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tasky-webapp
  template:
    metadata:
      labels:
        app: tasky-webapp
    spec:
      containers:
      - name: tasky-webapp
        image: martinroContainer.azurecr.io/tasky-webapp:latest
        ports:
        - containerPort: 8080
        env:
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: tasky-secret
              key: MONGODB_URI
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: tasky-secret
              key: SECRET_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: tasky-webapp-service
spec:
  type: LoadBalancer
  selector:
    app: tasky-webapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080